### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by 1j01** [1j01/tracky-mouse#58]
- [ ] Should mention on readme and website that ideas are tracked (extensively/in detail) on GitHub issues. Even if this project isn't ultimately successful, there's a lot of good ideas collected here.
- [ ] Try GitHub's Projects feature
- [ ] Plan out a good order for near-future features to tackle

**Comment by 1j01** [comment]
I'm trying out GitHub Projects privately for now.
It introduces noise to the issue tracker for every issue ("1j01 added this to Tracky Mouse 43 minutes ago
1j01 moved this to Backlog in Tracky Mouse 43 minutes ago"), noise which is visible only when I'm logged in, but which I'm assuming would be made visible to everyone if I make the Project public.

I'm not ...sure... what value I'm getting from this.  
Like, I want to:
- plan the near future issues to work on
- keep track of work that I have started in branches (making it more visible to encourage myself to merge things, tying up loose ends and ultimately avoiding re-work)
- communicate the plans for the project publicly

Ideally that communication would probably happen on the tracky mouse website...
which probably isn't going to happen unless there's a GitHub Projects widget I could embed (and it doesn't look terrible), if I'm using GitHub Projects.  
(and I don't know if a widget could even ever be satisfying compared to a properly written roadmap)

and then weighing the work that I would have to put into this system, and the noise of it...

I don't know, it's hard to guess how much work it would be, but if filing Issues is already meta work, Projects is meta-meta-work  
I feel like I'd be drinking the Kool-Aid, a bit...  

But I'll try it out for a bit to see if it's something I'd want to continue using.

--------------------

I selected a few issues that look good to work on next:

- https://github.com/1j01/tracky-mouse/issues/60 (I just added the CLI)
- https://github.com/1j01/tracky-mouse/issues/48 (I want to get the software into the hands of testers ASAP)
- https://github.com/1j01/tracky-mouse/issues/41 (sorta basic, might be a major annoyance, and toggling behavior is something important to focus on)
- https://github.com/1j01/tracky-mouse/issues/43 (could be a serious usability issue for someone who can't simply switch to a mouse if they mess up the settings)
- https://github.com/1j01/tracky-mouse/issues/51 (this is groundwork for adding features like facial and vocal gestures which would be much better to use than dwell clicking)
- https://github.com/1j01/tracky-mouse/issues/56 (I think I also saw it say "Start" while started, recently?)
